# DO NOT DELETE: Beginning of Haskell dependencies
Models/Param.o : Models/Param.hs
Models/Theoretical.o : Models/Theoretical.hs
Models/Theoretical.o : Models/Param.hi
Models/Imitational.o : Models/Imitational.hs
Models/Imitational.o : Models/Param.hi
Plot.o : Plot.hs
Plot.o : Models/Param.hi
Plot.o : Models/Imitational.hi
Plot.o : Models/Theoretical.hi
GUI.o : GUI.hs
GUI.o : Plot.hi
GUI.o : Models/Param.hi
Main.o : Main.hs
Main.o : GUI.hi
# DO NOT DELETE: End of Haskell dependencies
